### ISSUE TITLE
OpenStreetMaps support

### ISSUE THREAD

**Issue by samsk** [LINKIWI/orion-web#3]
First, great project - owntracks missed smth. like that.
Could you please implement OpenStreetMaps or Google Maps or smth. map support ?
Mapbox is great, but looking on its pricing page https://www.mapbox.com/pricing/, I need a commercial license to use it, what makes it usage really expensive.

Two of three conditions apply:
- Private web app or website with restricted access
- Asset tracking app or website to monitor people or things

And with OSM makes IMHO use of Owntracks+Orion really sense, because if I want to self-host gps tracking, I prefer also to self-host maps.

**Comment by LINKIWI** [comment]
[Mapbox uses OpenStreetMaps as a data source](https://www.mapbox.com/help/how-mapbox-data-works/).

Other than that, the [data visualization library](http://uber.github.io/deck.gl/) that powers Orion is built on top of Mapbox, and rewriting that to support a different map provider is not planned.

**Comment by samsk** [comment]
Ok, thanks. 
But you've maybe misread the real problem. The problem is that using of MapBox with Orion, requires for anyone to obtain its Commercial Plan. That is minimum 499$ / month. A little bit too much for tracking 2-3 persons ;-)

**Comment by Natanji** [comment]
You don't need a commercial plan. You can just use the free version, it offers enough API access really. Doesn't it @samsk?

**Comment by samsk** [comment]
Its not about number of requests !
Please, read mapbox pricing page - section 'When do I need commercial license?'
If I read correctly, then any tracking app/web requires commercional license.
Also if the web is private - you need a license. I doubt that you expose your positions publicly on the web, its surely restricted by password or whatever.

So if using orion, you need to pay commercial license ;(
Or am I wrong ?

**Comment by Natanji** [comment]
You are wrong; as you can see in issue #33, there is currently no authenticated access to the map data. orion-web *does* currently publish all your tracked location data for everyone on the web.

I only saw this Mapbox limitation now, so I guess this might severely limit the chances that #33 can easily be implemented. In the end, this probably means that if orion-web is supposed to ever be actually privately useable without the huge operating costs of a Mapbox license, it needs to be rewritten to use some other service/library than Mapbox.

**Comment by samsk** [comment]
Orion maybe publishes data for everyone, but the one who is self-hosting it, might put it behind some basic auth via apache .htaccess or similar.
IMHO, users and target audience of owntracks/orion are privacy minded people - people who dont want to share they position on google or other 3rd party service. I'm pretty sure they make it private (I would), and therfore are they obligated to use commercial license for it.

And even if they dont, tracking people/things/assets requires commercial license.

I dont see a way how to run orion without commercional license, and not break some mapbox usage permissions.

**Comment by Natanji** [comment]
> IMHO, users and target audience of owntracks/orion are privacy minded people - people who dont want to share they position on google or other 3rd party service. I'm pretty sure they make it private (I would), and therfore are they obligated to use commercial license for it.

Well, I think there is a loophole on that. orion-web is just a static website, and can in fact be publicly accessible by anyone on the internet. It's also the only part that uses Mapbox. So once your browser has completely downloaded the website (and thereby the mapbox map), it will *afterwards* try to access /api/users and /api/locations *from within your browser*. If you authenticate access to these two locations, then your browser will ask for authentication e.g. via HTTP basic auth, and afterwards your browser will use this data to display the map. But this authentication is optional, the static website is still accessible without this data, it just won't be very interesting. So it doesn't violate Mapbox TOS here: the web app/website hosting orion-web is not private and doesn't need to be private in any way. Just the data it accesses is.

> And even if they dont, tracking people/things/assets requires commercial license.

...however, this part I believe *is* true. Maybe you can open a new issue for that, such that "you need a commercial license" is added to the installation instructions? Because right now everyone who even follows the installation instructions without a paid Mapbox account is factually breaking the Mapbox TOS.
